CREATE TABLE IF NOT EXISTS listings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source TEXT NOT NULL,
    source_listing_id TEXT,
    canonical_url TEXT,
    identity_key TEXT NOT NULL,
    title TEXT,
    property_type TEXT,
    address TEXT,
    neighborhood TEXT,
    city TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    location_precision TEXT NOT NULL DEFAULT 'source'
        CHECK (location_precision IN ('source', 'neighborhood')),
    area_m2 NUMERIC(10, 2),
    bedrooms NUMERIC(4, 1),
    bathrooms NUMERIC(4, 1),
    parking_spaces NUMERIC(4, 1),
    first_seen_at TIMESTAMPTZ NOT NULL,
    last_seen_at TIMESTAMPTZ NOT NULL,
    current_status TEXT NOT NULL DEFAULT 'active'
        CHECK (current_status IN ('active', 'suspect', 'removed')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT listings_source_identity_key UNIQUE (source, identity_key)
);

ALTER TABLE listings ADD COLUMN IF NOT EXISTS property_type TEXT;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS location_precision TEXT NOT NULL DEFAULT 'source';

CREATE INDEX IF NOT EXISTS listings_status_neighborhood_idx
    ON listings (current_status, city, neighborhood);
CREATE INDEX IF NOT EXISTS listings_source_listing_id_idx
    ON listings (source, source_listing_id)
    WHERE source_listing_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS observations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id BIGINT NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
    observed_at TIMESTAMPTZ NOT NULL,
    rent_price NUMERIC(12, 2),
    condo_fee NUMERIC(12, 2),
    iptu NUMERIC(12, 2),
    total_price NUMERIC(12, 2),
    price_m2 NUMERIC(12, 2),
    available BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT observations_listing_observed_at UNIQUE (listing_id, observed_at)
);

CREATE INDEX IF NOT EXISTS observations_observed_at_idx
    ON observations (observed_at);

CREATE TABLE IF NOT EXISTS collection_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source TEXT NOT NULL,
    started_at TIMESTAMPTZ NOT NULL,
    finished_at TIMESTAMPTZ,
    status TEXT NOT NULL DEFAULT 'running'
        CHECK (status IN ('running', 'success', 'failed')),
    records_found INTEGER NOT NULL DEFAULT 0 CHECK (records_found >= 0),
    records_new INTEGER NOT NULL DEFAULT 0 CHECK (records_new >= 0),
    records_updated INTEGER NOT NULL DEFAULT 0 CHECK (records_updated >= 0),
    records_missing INTEGER NOT NULL DEFAULT 0 CHECK (records_missing >= 0),
    error_message TEXT,
    metrics_json TEXT NOT NULL DEFAULT '{}'
);

ALTER TABLE collection_runs ADD COLUMN IF NOT EXISTS metrics_json TEXT NOT NULL DEFAULT '{}';
